/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
	| "Pacific/Midway"
	| "Pacific/Niue"
	| "Pacific/Honolulu"
	| "Pacific/Rarotonga"
	| "America/Anchorage"
	| "Pacific/Gambier"
	| "America/Los_Angeles"
	| "America/Tijuana"
	| "America/Denver"
	| "America/Phoenix"
	| "America/Chicago"
	| "America/Guatemala"
	| "America/New_York"
	| "America/Bogota"
	| "America/Caracas"
	| "America/Santiago"
	| "America/Buenos_Aires"
	| "America/Sao_Paulo"
	| "Atlantic/South_Georgia"
	| "Atlantic/Azores"
	| "Atlantic/Cape_Verde"
	| "Europe/London"
	| "Europe/Berlin"
	| "Africa/Lagos"
	| "Europe/Athens"
	| "Africa/Cairo"
	| "Europe/Moscow"
	| "Asia/Riyadh"
	| "Asia/Dubai"
	| "Asia/Baku"
	| "Asia/Karachi"
	| "Asia/Tashkent"
	| "Asia/Calcutta"
	| "Asia/Dhaka"
	| "Asia/Almaty"
	| "Asia/Jakarta"
	| "Asia/Bangkok"
	| "Asia/Shanghai"
	| "Asia/Singapore"
	| "Asia/Tokyo"
	| "Asia/Seoul"
	| "Australia/Brisbane"
	| "Australia/Sydney"
	| "Pacific/Guam"
	| "Pacific/Noumea"
	| "Pacific/Auckland"
	| "Pacific/Fiji";

export interface Config {
	auth: {
		users: UserAuthOperations;
	};
	blocks: {
		richText: RichText;
	};
	collections: {
		users: User;
		pages: Page;
		posts: Post;
		tags: Tag;
		"mcpx-api-keys": McpxApiKey;
		"payload-kv": PayloadKv;
		"payload-locked-documents": PayloadLockedDocument;
		"payload-preferences": PayloadPreference;
		"payload-migrations": PayloadMigration;
	};
	collectionsJoins: {};
	collectionsSelect: {
		users: UsersSelect<false> | UsersSelect<true>;
		pages: PagesSelect<false> | PagesSelect<true>;
		posts: PostsSelect<false> | PostsSelect<true>;
		tags: TagsSelect<false> | TagsSelect<true>;
		"mcpx-api-keys": McpxApiKeysSelect<false> | McpxApiKeysSelect<true>;
		"payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
		"payload-locked-documents":
			PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
		"payload-preferences":
			PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
		"payload-migrations":
			PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
	};
	db: {
		defaultIDType: number;
	};
	fallbackLocale:
		| ("false" | "none" | "null")
		| false
		| null
		| ("en" | "de")
		| ("en" | "de")[];
	globals: {
		"site-settings": SiteSetting;
	};
	globalsSelect: {
		"site-settings": SiteSettingsSelect<false> | SiteSettingsSelect<true>;
	};
	locale: "en" | "de";
	widgets: {
		collections: CollectionsWidget;
	};
	user: User;
	jobs: {
		tasks: unknown;
		workflows: unknown;
	};
}
export interface UserAuthOperations {
	forgotPassword: {
		email: string;
		password: string;
	};
	login: {
		email: string;
		password: string;
	};
	registerFirstUser: {
		email: string;
		password: string;
	};
	unlock: {
		email: string;
		password: string;
	};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "richText".
 */
export interface RichText {
	content: {
		root: {
			type: string;
			children: {
				type: any;
				version: number;
				[k: string]: unknown;
			}[];
			direction: ("ltr" | "rtl") | null;
			format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
			indent: number;
			version: number;
		};
		[k: string]: unknown;
	};
	id?: string | null;
	blockName?: string | null;
	blockType: "richText";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
	id: number;
	updatedAt: string;
	createdAt: string;
	email: string;
	resetPasswordToken?: string | null;
	resetPasswordExpiration?: string | null;
	salt?: string | null;
	hash?: string | null;
	loginAttempts?: number | null;
	lockUntil?: string | null;
	sessions?:
		| {
				id: string;
				createdAt?: string | null;
				expiresAt: string;
		  }[]
		| null;
	password?: string | null;
	collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
	id: number;
	title: string;
	slug: string;
	layout: {
		color?: ("light" | "dark") | null;
		sections: (
			| {
					identifier?: string | null;
					modules?:
						| (
								| {
										title: {
											root: {
												type: string;
												children: {
													type: any;
													version: number;
													[k: string]: unknown;
												}[];
												direction: ("ltr" | "rtl") | null;
												format:
													| "left"
													| "start"
													| "center"
													| "right"
													| "end"
													| "justify"
													| "";
												indent: number;
												version: number;
											};
											[k: string]: unknown;
										};
										body?: {
											root: {
												type: string;
												children: {
													type: any;
													version: number;
													[k: string]: unknown;
												}[];
												direction: ("ltr" | "rtl") | null;
												format:
													| "left"
													| "start"
													| "center"
													| "right"
													| "end"
													| "justify"
													| "";
												indent: number;
												version: number;
											};
											[k: string]: unknown;
										} | null;
										imageSize?: ("small" | "large") | null;
										id?: string | null;
										blockName?: string | null;
										blockType: "hero";
								  }
								| RichText
						  )[]
						| null;
					id?: string | null;
					blockName?: string | null;
					blockType: "sectionWrapper";
			  }
			| {
					content: {
						root: {
							type: string;
							children: {
								type: any;
								version: number;
								[k: string]: unknown;
							}[];
							direction: ("ltr" | "rtl") | null;
							format:
								"left" | "start" | "center" | "right" | "end" | "justify" | "";
							indent: number;
							version: number;
						};
						[k: string]: unknown;
					};
					id?: string | null;
					blockName?: string | null;
					blockType: "richText";
			  }
		)[];
	};
	meta?: {
		title?: string | null;
	};
	updatedAt: string;
	createdAt: string;
	_status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
	id: number;
	title: string;
	content?: {
		root: {
			type: string;
			children: {
				type: any;
				version: number;
				[k: string]: unknown;
			}[];
			direction: ("ltr" | "rtl") | null;
			format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
			indent: number;
			version: number;
		};
		[k: string]: unknown;
	} | null;
	tags?: (number | Tag)[] | null;
	updatedAt: string;
	createdAt: string;
	_status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
	id: number;
	name: string;
	updatedAt: string;
	createdAt: string;
}
/**
 * Keys for MCP clients. Each key acts as its user and may only do what its capabilities allow.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcpx-api-keys".
 */
export interface McpxApiKey {
	id: number;
	/**
	 * The user this key acts as.
	 */
	user: number | User;
	/**
	 * What this key is used for.
	 */
	label: string;
	/**
	 * Disabled keys are refused without revoking them.
	 */
	enabled?: boolean | null;
	/**
	 * Generated when the key is created. Send it as `Authorization: Bearer <key>`.
	 */
	apiKey?: string | null;
	apiKeyIndex?: string | null;
	/**
	 * What this key may do. Unchecked means refused, whatever the plugin config allows.
	 */
	capabilities?: {
		collections?: {
			pages?: {
				/**
				 * Describe, find and read documents.
				 */
				read?: boolean | null;
				/**
				 * Create, patch and validate drafts.
				 */
				write?: boolean | null;
			};
			posts?: {
				/**
				 * Describe, find and read documents.
				 */
				read?: boolean | null;
				/**
				 * Create, patch and validate drafts.
				 */
				write?: boolean | null;
			};
			tags?: {
				/**
				 * Describe, find and read documents.
				 */
				read?: boolean | null;
			};
		};
		globals?: {
			siteSettings?: {
				/**
				 * Describe and read this global.
				 */
				read?: boolean | null;
				/**
				 * Patch and validate this global's draft.
				 */
				write?: boolean | null;
			};
		};
	};
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
	id: number;
	key: string;
	data:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
	id: number;
	document?:
		| ({
				relationTo: "users";
				value: number | User;
		  } | null)
		| ({
				relationTo: "pages";
				value: number | Page;
		  } | null)
		| ({
				relationTo: "posts";
				value: number | Post;
		  } | null)
		| ({
				relationTo: "tags";
				value: number | Tag;
		  } | null)
		| ({
				relationTo: "mcpx-api-keys";
				value: number | McpxApiKey;
		  } | null);
	globalSlug?: string | null;
	user: {
		relationTo: "users";
		value: number | User;
	};
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
	id: number;
	user: {
		relationTo: "users";
		value: number | User;
	};
	key?: string | null;
	value?:
		| {
				[k: string]: unknown;
		  }
		| unknown[]
		| string
		| number
		| boolean
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
	id: number;
	name?: string | null;
	batch?: number | null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
	updatedAt?: T;
	createdAt?: T;
	email?: T;
	resetPasswordToken?: T;
	resetPasswordExpiration?: T;
	salt?: T;
	hash?: T;
	loginAttempts?: T;
	lockUntil?: T;
	sessions?:
		| T
		| {
				id?: T;
				createdAt?: T;
				expiresAt?: T;
		  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
	title?: T;
	slug?: T;
	layout?:
		| T
		| {
				color?: T;
				sections?:
					| T
					| {
							sectionWrapper?:
								| T
								| {
										identifier?: T;
										modules?:
											| T
											| {
													hero?:
														| T
														| {
																title?: T;
																body?: T;
																imageSize?: T;
																id?: T;
																blockName?: T;
														  };
											  };
										id?: T;
										blockName?: T;
								  };
							richText?:
								| T
								| {
										content?: T;
										id?: T;
										blockName?: T;
								  };
					  };
		  };
	meta?:
		| T
		| {
				title?: T;
		  };
	updatedAt?: T;
	createdAt?: T;
	_status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
	title?: T;
	content?: T;
	tags?: T;
	updatedAt?: T;
	createdAt?: T;
	_status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
	name?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mcpx-api-keys_select".
 */
export interface McpxApiKeysSelect<T extends boolean = true> {
	user?: T;
	label?: T;
	enabled?: T;
	apiKey?: T;
	apiKeyIndex?: T;
	capabilities?:
		| T
		| {
				collections?:
					| T
					| {
							pages?:
								| T
								| {
										read?: T;
										write?: T;
								  };
							posts?:
								| T
								| {
										read?: T;
										write?: T;
								  };
							tags?:
								| T
								| {
										read?: T;
								  };
					  };
				globals?:
					| T
					| {
							siteSettings?:
								| T
								| {
										read?: T;
										write?: T;
								  };
					  };
		  };
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
	key?: T;
	data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
	document?: T;
	globalSlug?: T;
	user?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
	user?: T;
	key?: T;
	value?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
	name?: T;
	batch?: T;
	updatedAt?: T;
	createdAt?: T;
}
/**
 * Settings shared by every page, such as the site title.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
	id: number;
	/**
	 * Shown in the browser tab and in search results.
	 */
	title: string;
	sections?: RichText[] | null;
	_status?: ("draft" | "published") | null;
	updatedAt?: string | null;
	createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
	title?: T;
	sections?: T | {};
	_status?: T;
	updatedAt?: T;
	createdAt?: T;
	globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
	data?: {
		[k: string]: unknown;
	};
	width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
	[k: string]: unknown;
}

declare module "payload" {
	export interface GeneratedTypes extends Config {}
}
